### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by scorypto** [reduxd/atom-itunes#1]
Steps to Reproduce:
1. Open Atom
2. Press Alt+Ctrl+P and select Itunes: Open
3. This error is shown.

**Atom Version**: 0.182.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [iTunes](https://github.com/reduxd/atom-itunes) package, v0.2.0
### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:94

Error: write EPIPE
  at exports._errnoException (util.js:753:11)
  at Socket._writeGeneric (net.js:681:26)
  at Socket._write (net.js:700:8)
  at doWrite (_stream_writable.js:303:12)
  at writeOrBuffer (_stream_writable.js:290:5)
  at Socket.Writable.write (_stream_writable.js:219:11)
  at Socket.write (net.js:625:40)
  at runApplescript (C:\Users\yrajpurohit\.atom\packages\iTunes\node_modules\applescript\lib\applescript.js:58:23)
  at Object.execString (C:\Users\yrajpurohit\.atom\packages\iTunes\node_modules\applescript\lib\applescript.js:19:10)
  at C:\Users\yrajpurohit\.atom\packages\iTunes\lib\itunes-desktop.coffee:47:19

```
### Commands

```
     -32:27.1 autocomplete-plus:confirm (atom-text-editor.editor)
 13x -32:23.8 autocomplete-plus:select-next (atom-text-editor.editor)
  7x -32:20.9 autocomplete-plus:select-previous (atom-text-editor.editor)
     -32:19.3 autocomplete-plus:confirm (atom-text-editor.editor)
  4x -32:17.6 editor:delete-to-beginning-of-word (atom-text-editor.editor)
     -32:15.9 core:backspace (atom-text-editor.editor)
     -32:15.1 core:save (atom-text-editor.editor)
     -31:15.2 core:paste (atom-text-editor.editor.mini)
     -31:13.3 core:confirm (atom-text-editor.editor.mini)
     -30:55.1 command-palette:toggle (div.settings-view.pane-item)
     -30:52.7 core:confirm (atom-text-editor.editor.mini)
     -30:52.7 itunes:next (div.settings-view.pane-item)
     -30:40.2 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-itg-dark-syntax.theme-itg-flat-dark)
     -30:09.5 command-palette:toggle (atom-text-editor.editor)
     -30:06.5 core:confirm (atom-text-editor.editor.mini)
     -30:06.5 itunes:open (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "itg-flat-dark",
      "itg-dark-syntax"
    ],
    "disabledPackages": [
      "terminal-status"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
color-picker, v1.4.4
file-icons, v1.4.11
itg-dark-syntax, v0.3.0
itg-flat-dark, v0.1.1
iTunes, v0.2.0
linter-javac, v0.1.3
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by lapin-b** [comment]
I've got the same issue. I paste my config:

Steps to reproduce:
1. Open the command palette (with ctrl-shift-p)
2. Type "itunes play"
3. Error is shown

**Atom Version**: 0.204.0
**System**: Unknown Windows Version
**Thrown From**: [iTunes](https://github.com/reduxd/atom-itunes) package, v0.2.0

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
  at exports._errnoException (util.js:734:11)
  at Socket._writeGeneric (net.js:668:26)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at runApplescript (C:\Users\Mathias\.atom\packages\iTunes\node_modules\applescript\lib\applescript.js:58:23)
  at Object.execString (C:\Users\Mathias\.atom\packages\iTunes\node_modules\applescript\lib\applescript.js:19:10)
  at C:\Users\Mathias\.atom\packages\iTunes\lib\itunes-desktop.coffee:47:19

```

### Commands

```
     -0:11.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:09.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.8.0 itunes:play (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "code-links"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
auto-detect-indentation, v0.4.2
emmet, v2.3.10
event-watch, v3.7.4
iTunes, v0.2.0
language-blade, v0.14.0
laravel, v0.7.0
linter, v0.12.6
linter-php, v0.0.15
project-manager, v1.15.7
timecop, v0.31.0
typewriter-sounds, v0.1.0

# Dev
No dev packages
```
